name: 02 - Workflow Event
on: pull_request
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event name: ${{ github.event_name }}"
          
