name: 04 - Using Actions
on : push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
  Printing-Folders: 
      runs-on: ubuntu-latest
      steps:
      - name: Printing Folders
        run:  |
          ls -ltr
